config:
   uri: http:localhost:8888/

spring:
   application:
      name: weather-area-code-service
   cloud:
      import: optional:configserver:${config.uri}

management:
   endpoints:
      web:
         exposure:
            include: "*"
      