server:
   port: 8888

spring:
   application:
      name: config-weather-catalogue
   cloud:
      config:
         server:
            git:
               uri: https://github.com/gedaddict/config-repo.git
